spring:
  application:
    name: agenda
  datasource:
    url: jdbc:postgresql://localhost:5432/agenda_db
    username: postgres
    password: mvcsfut10
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true